export type {
  CrossAxisMapping,
  DevelopmentStatusDefinition,
  FontAxes,
  FontAxis,
  FontData,
  FontExportInstance,
  FontInfo,
  FontInfoCustomDataValue,
  FontProjectSettings,
  FontSource,
  GlyphAnchor,
  GlyphComponentRef,
  GlyphCustomData,
  GlyphData,
  GlyphGuideline,
  GlyphHint,
  GlyphImage,
  GlyphLayerContent,
  GlyphLayerData,
  GlyphMetrics,
  GlyphSourceData,
  GlyphVerticalMetrics,
  KerningGroup,
  KerningPair,
  KumikoColor,
  NodeType,
  OffCurvePathNode,
  OnCurveNodeType,
  OnCurvePathNode,
  PathData,
  PathNode,
  PathNodeKind,
  PathSegmentType,
} from '@/domain/types'
export {
  ACTIVE_LAYER_FALLBACK,
  activeLayer,
  ensureActiveLayer,
  ensureLoadedActiveLayer,
  getActiveLayer,
  getActiveLayerId,
  getGlyphLayer,
  normalizeGlyphToLayers,
  setGlyphActiveLayer,
  withActiveLayer,
} from '@/domain/glyphLayer'
export {
  createBackupLayer,
  deleteBackupLayer,
  duplicateLayer,
  listGlyphLayers,
  promoteBackupToMaster,
  renameBackupLayer,
} from '@/domain/glyphLayerOps'
export {
  createOffCurveNode,
  createOnCurveNode,
  findNode,
  findPath,
  generateId,
  getEffectiveNodeType,
  getGlyphXBounds,
  getNodeSegmentType,
  getNodeType,
  isOffCurveNode,
  isOnCurveNode,
  isPathEndpointNode,
  lerp,
  orientOpenPathNodesForConnection,
  recomputeGlyphSidebearings,
  setNodeSegmentType,
  setNodeType,
  translateGlyphHorizontally,
  wouldCreateComponentCycle,
} from '@/domain/glyphGeometry'
export {
  createGlyphCopies,
  createGlyphCopyId,
  insertGlyphIdsAfter,
} from '@/domain/glyphCopy'
export {
  type ReconnectEndpoint,
  pairEndpointsByContinuity,
  pairNearestEndpoints,
  performReconnect,
} from '@/domain/reconnectNodes'
export { deterministicStringify } from '@/domain/deterministicStringify'
export {
  getGlyphComponentGlyphIds,
  hasLegacyGlyphGeometry,
  isGlyphGeometryLoaded,
} from '@/domain/glyphGeometryState'
export {
  type ComponentMatrix,
  componentMatrixToRefFields,
  composeComponentMatrix,
  getComponentMatrix,
  isIdentityComponentMatrix,
  translateComponentRef,
  withComponentMatrix,
} from '@/domain/componentTransform'
