import type { FeaNode } from 'src/lib/openTypeFeatures/feaAst'
import type {
  FeatureEntry,
  LookupRecord,
  OpenTypeFeaturesState,
  Rule,
} from 'src/lib/openTypeFeatures/types'

const headerComments = [
  'Generated by Kumiko Font Editor.',
  'This file is disposable build output.',
  'It is not guaranteed to match any original feature source imported from a compiled font.',
]

const ruleToNode = (rule: Rule): FeaNode | null => {
  switch (rule.kind) {
    case 'singleSubstitution':
      return {
        kind: 'Substitution',
        ruleId: rule.id,
        pattern: [rule.target],
        replacement: [rule.replacement],
      }
    case 'multipleSubstitution':
      return {
        kind: 'Substitution',
        ruleId: rule.id,
        pattern: [{ kind: 'glyph', glyph: rule.target }],
        replacement: rule.replacement,
      }
    case 'alternateSubstitution':
      return {
        kind: 'Substitution',
        ruleId: rule.id,
        pattern: [{ kind: 'glyph', glyph: rule.target }],
        replacement: [],
        alternates: rule.alternates,
      }
    case 'ligatureSubstitution':
      return {
        kind: 'Substitution',
        ruleId: rule.id,
        pattern: rule.components.map((glyph) => ({ kind: 'glyph', glyph })),
        replacement: [rule.replacement],
      }
    case 'singlePositioning':
      return {
        kind: 'Positioning',
        ruleId: rule.id,
        left: rule.target,
        firstValue: rule.value,
      }
    case 'pairPositioning':
      return {
        kind: 'Positioning',
        ruleId: rule.id,
        left: rule.left,
        right: rule.right,
        firstValue: rule.firstValue,
        secondValue: rule.secondValue,
      }
    default:
      return {
        kind: 'Comment',
        value: `Unsupported generated rule kind: ${rule.kind}`,
      }
  }
}

const lookupToBlock = (lookup: LookupRecord): FeaNode => ({
  kind: 'LookupBlock',
  name: lookup.name,
  lookupId: lookup.id,
  statements: lookup.rules
    .map(ruleToNode)
    .filter((node): node is FeaNode => Boolean(node)),
})

const featureEntryStatements = (
  entry: FeatureEntry,
  lookupById: Map<string, LookupRecord>
): FeaNode[] => {
  const statements: FeaNode[] = [
    { kind: 'ScriptStatement', script: entry.script },
    { kind: 'LanguageStatement', language: entry.language },
  ]

  for (const lookupId of entry.lookupIds) {
    const lookup = lookupById.get(lookupId)
    if (lookup) {
      statements.push({
        kind: 'Raw',
        value: `  lookup ${lookup.name};`,
      })
    }
  }
  return statements
}

export const buildFeaDocument = (state: OpenTypeFeaturesState) => {
  const lookupById = new Map(state.lookups.map((lookup) => [lookup.id, lookup]))
  const activeLookupIds = new Set(
    state.features
      .filter((feature) => feature.isActive)
      .flatMap((feature) => feature.entries.flatMap((entry) => entry.lookupIds))
  )

  const statements: FeaNode[] = [
    ...headerComments.map((value) => ({ kind: 'Comment' as const, value })),
    ...(state.rawPrelude
      ? [{ kind: 'Raw' as const, value: state.rawPrelude }]
      : []),
    ...state.languagesystems.map((languageSystem) => ({
      kind: 'LanguageSystem' as const,
      script: languageSystem.script,
      language: languageSystem.language,
    })),
    ...state.glyphClasses.map((glyphClass) => ({
      kind: 'GlyphClass' as const,
      name: glyphClass.name,
      glyphs: glyphClass.glyphs,
      classId: glyphClass.id,
    })),
    ...state.markClasses.flatMap((markClass) =>
      markClass.marks.map((mark) => ({
        kind: 'MarkClass' as const,
        glyph: mark.glyph,
        anchor: mark.anchor,
        className: markClass.name,
      }))
    ),
    ...state.lookups
      .filter((lookup) => activeLookupIds.has(lookup.id))
      .map(lookupToBlock),
    ...state.features
      .filter((feature) => feature.isActive)
      .map((feature) => ({
        kind: 'FeatureBlock' as const,
        tag: feature.tag,
        featureId: feature.id,
        statements: feature.entries.flatMap((entry) =>
          featureEntryStatements(entry, lookupById)
        ),
      })),
  ]

  return {
    kind: 'Document' as const,
    statements,
  }
}
