import type { FeaNode, MarkAttachment } from 'src/lib/openTypeFeatures/feaAst'
import { escapeFeaNameString } from 'src/lib/openTypeFeatures/feaFormat'
import { getRawFeatureText } from 'src/lib/openTypeFeatures/rawFeatureSnippets'
import type {
  FeatureEntry,
  FeatureParamName,
  FeatureParams,
  FeatureRecord,
  LookupFlagIR,
  LookupRecord,
  OpenTypeFeaturesState,
  Rule,
} from 'src/lib/openTypeFeatures/types'
import { getNestedLookupReferences } from 'src/lib/openTypeFeatures/ruleReferences'

const headerComments = [
  'Generated by Kumiko Font Editor.',
  'This file is disposable build output.',
  'It is not guaranteed to match any original feature source imported from a compiled font.',
]

const hasLookupFlags = (flags: LookupFlagIR) =>
  Boolean(
    flags.rightToLeft ||
    flags.ignoreBaseGlyphs ||
    flags.ignoreLigatures ||
    flags.ignoreMarks ||
    flags.markAttachmentType ||
    flags.useMarkFilteringSet
  )

const mapMarkAttachments = (
  anchors: Record<string, { x: number; y: number }>,
  markClassNameById: Map<string, string>
): MarkAttachment[] =>
  Object.entries(anchors)
    .map(([markClassId, anchor]) => {
      const markClassName = markClassNameById.get(markClassId)
      return markClassName ? { markClassName, anchor } : null
    })
    .filter((entry): entry is MarkAttachment => Boolean(entry))

const missingMarkClassIds = (
  anchors: Record<string, { x: number; y: number }>,
  markClassNameById: Map<string, string>
) =>
  Object.keys(anchors).filter(
    (markClassId) => !markClassNameById.has(markClassId)
  )

const markRuleMissingClassComment = (rule: Rule, missingIds: string[]) => ({
  kind: 'Comment' as const,
  value: `Cannot serialize rule ${rule.id}: missing mark class ${missingIds.join(', ')}`,
})

const markRuleMissingAnchorsComment = (rule: Rule) => ({
  kind: 'Comment' as const,
  value: `Cannot serialize rule ${rule.id}: mark positioning rule has no mark anchors`,
})

const ruleToNode = (
  rule: Rule,
  markClassNameById: Map<string, string>,
  lookupNameById: Map<string, string>
): FeaNode | null => {
  switch (rule.kind) {
    case 'singleSubstitution':
      return {
        kind: 'Substitution',
        ruleId: rule.id,
        pattern: [rule.target],
        replacement: [rule.replacement],
      }
    case 'multipleSubstitution':
      return {
        kind: 'Substitution',
        ruleId: rule.id,
        pattern: [{ kind: 'glyph', glyph: rule.target }],
        replacement: rule.replacement,
      }
    case 'alternateSubstitution':
      return {
        kind: 'Substitution',
        ruleId: rule.id,
        pattern: [{ kind: 'glyph', glyph: rule.target }],
        replacement: [],
        alternates: rule.alternates,
      }
    case 'ligatureSubstitution':
      return {
        kind: 'Substitution',
        ruleId: rule.id,
        pattern: rule.components.map((glyph) => ({ kind: 'glyph', glyph })),
        replacement: [rule.replacement],
      }
    case 'singlePositioning':
      return {
        kind: 'Positioning',
        ruleId: rule.id,
        left: rule.target,
        firstValue: rule.value,
      }
    case 'pairPositioning':
      return {
        kind: 'Positioning',
        ruleId: rule.id,
        left: rule.left,
        right: rule.right,
        firstValue: rule.firstValue,
        secondValue: rule.secondValue,
      }
    case 'contextualSubstitution':
      return {
        kind: 'ContextualSubstitution',
        ruleId: rule.id,
        backtrack: rule.backtrack,
        input: rule.input.map((entry) => ({
          selector: entry.selector,
          lookupNames: (entry.lookupIds ?? [])
            .map((lookupId) => lookupNameById.get(lookupId))
            .filter((name): name is string => Boolean(name)),
        })),
        lookahead: rule.lookahead,
      }
    case 'reverseChainingSingleSubstitution':
      return {
        kind: 'ReverseChainingSingleSubstitution',
        ruleId: rule.id,
        backtrack: rule.backtrack,
        target: rule.target,
        lookahead: rule.lookahead,
        replacement: rule.replacement,
      }
    case 'contextualPositioning':
      return {
        kind: 'ContextualPositioning',
        ruleId: rule.id,
        backtrack: rule.backtrack,
        input: rule.input.map((entry) => ({
          selector: entry.selector,
          lookupNames: (entry.lookupIds ?? [])
            .map((lookupId) => lookupNameById.get(lookupId))
            .filter((name): name is string => Boolean(name)),
        })),
        lookahead: rule.lookahead,
      }
    case 'markToBase': {
      const missingIds = missingMarkClassIds(rule.anchors, markClassNameById)
      if (missingIds.length > 0) {
        return markRuleMissingClassComment(rule, missingIds)
      }
      const marks = mapMarkAttachments(rule.anchors, markClassNameById)
      if (marks.length === 0) {
        return markRuleMissingAnchorsComment(rule)
      }
      return {
        kind: 'MarkToBase',
        ruleId: rule.id,
        base: rule.baseGlyphs,
        marks,
      }
    }
    case 'markToMark': {
      const missingIds = missingMarkClassIds(rule.anchors, markClassNameById)
      if (missingIds.length > 0) {
        return markRuleMissingClassComment(rule, missingIds)
      }
      const marks = mapMarkAttachments(rule.anchors, markClassNameById)
      if (marks.length === 0) {
        return markRuleMissingAnchorsComment(rule)
      }
      return {
        kind: 'MarkToMark',
        ruleId: rule.id,
        baseMark: rule.baseMarks,
        marks,
      }
    }
    case 'markToLigature': {
      const missingIds = rule.componentAnchors.flatMap((componentAnchors) =>
        missingMarkClassIds(componentAnchors, markClassNameById)
      )
      if (missingIds.length > 0) {
        return markRuleMissingClassComment(rule, missingIds)
      }
      const componentMarks = rule.componentAnchors.map((componentAnchors) =>
        mapMarkAttachments(componentAnchors, markClassNameById)
      )
      if (
        componentMarks.length === 0 ||
        componentMarks.some((marks) => marks.length === 0)
      ) {
        return markRuleMissingAnchorsComment(rule)
      }
      return {
        kind: 'MarkToLigature',
        ruleId: rule.id,
        ligature: rule.ligatures,
        componentMarks,
      }
    }
    case 'cursivePositioning':
      return rule.entryAnchor || rule.exitAnchor
        ? {
            kind: 'CursivePositioning',
            ruleId: rule.id,
            glyphs: rule.glyphs,
            entryAnchor: rule.entryAnchor,
            exitAnchor: rule.exitAnchor,
          }
        : {
            kind: 'Comment',
            value: `Cannot serialize rule ${rule.id}: cursive positioning rule has no entry or exit anchor`,
          }
    default: {
      const unsupportedRule = rule as { kind: string }
      return {
        kind: 'Comment',
        value: `Unsupported generated rule kind: ${unsupportedRule.kind}`,
      }
    }
  }
}

const lookupToBlock = (
  lookup: LookupRecord,
  markClassNameById: Map<string, string>,
  glyphClassNameById: Map<string, string>,
  lookupNameById: Map<string, string>
): FeaNode => {
  const markAttachmentClassName = lookup.markAttachmentClassId
    ? glyphClassNameById.get(lookup.markAttachmentClassId)
    : undefined
  const markFilteringSetName = lookup.markFilteringSetClassId
    ? glyphClassNameById.get(lookup.markFilteringSetClassId)
    : undefined
  const missingMarkAttachmentClass =
    lookup.lookupFlag.markAttachmentType &&
    lookup.markAttachmentClassId &&
    !markAttachmentClassName
  const missingMarkFilteringSet =
    lookup.lookupFlag.useMarkFilteringSet &&
    lookup.markFilteringSetClassId &&
    !markFilteringSetName
  const serializableLookupFlag = {
    ...lookup.lookupFlag,
    ...(missingMarkAttachmentClass ? { markAttachmentType: false } : {}),
    ...(missingMarkFilteringSet ? { useMarkFilteringSet: false } : {}),
  }
  const statements: FeaNode[] = [
    ...(missingMarkAttachmentClass
      ? [
          {
            kind: 'Comment' as const,
            value: `Cannot serialize MarkAttachmentType for lookup ${lookup.id}: missing glyph class ${lookup.markAttachmentClassId}`,
          },
        ]
      : []),
    ...(missingMarkFilteringSet
      ? [
          {
            kind: 'Comment' as const,
            value: `Cannot serialize UseMarkFilteringSet for lookup ${lookup.id}: missing glyph class ${lookup.markFilteringSetClassId}`,
          },
        ]
      : []),
    ...(hasLookupFlags(serializableLookupFlag)
      ? [
          {
            kind: 'LookupFlag' as const,
            flags: serializableLookupFlag,
            markAttachmentClassName,
            markFilteringSetName,
          },
        ]
      : []),
    ...lookup.rules
      .map((rule) => ruleToNode(rule, markClassNameById, lookupNameById))
      .filter((node): node is FeaNode => Boolean(node)),
  ]

  return {
    kind: 'LookupBlock',
    name: lookup.name,
    lookupId: lookup.id,
    statements,
  }
}

const featureEntryStatements = (
  entry: FeatureEntry,
  lookupById: Map<string, LookupRecord>
): FeaNode[] => {
  const statements: FeaNode[] = [
    { kind: 'ScriptStatement', script: entry.script },
    { kind: 'LanguageStatement', language: entry.language },
  ]

  for (const lookupId of entry.lookupIds) {
    const lookup = lookupById.get(lookupId)
    if (lookup) {
      statements.push({
        kind: 'Raw',
        value: `  lookup ${lookup.name};`,
      })
    }
  }
  return statements
}

const lookupReferenceStatement = (lookup: LookupRecord): FeaNode => ({
  kind: 'Raw',
  value: `  lookup ${lookup.name};`,
})

const formatNameLine = (name: FeatureParamName, indent: string) =>
  `${indent}name "${escapeFeaNameString(name.text)}";`

const formatDecipoints = (value: number) => (value / 10).toFixed(1)

const formatCharacter = (codePoint: number) =>
  `0x${codePoint.toString(16).toUpperCase().padStart(4, '0')}`

const featureParamsStatements = (
  params: FeatureParams | undefined
): FeaNode[] => {
  if (!params) return []
  const lines: string[] = []

  if (params.kind === 'stylisticSet') {
    if (params.names.length === 0) return []
    lines.push('  featureNames {')
    for (const name of params.names) {
      lines.push(formatNameLine(name, '    '))
    }
    lines.push('  };')
  }

  if (params.kind === 'characterVariant') {
    const groupLines: string[] = []
    const pushNameGroup = (label: string, names: FeatureParamName[]) => {
      if (names.length === 0) return
      groupLines.push(`    ${label} {`)
      for (const name of names) {
        groupLines.push(formatNameLine(name, '      '))
      }
      groupLines.push('    };')
    }
    pushNameGroup('FeatUILabelNameID', params.featUiLabelNames)
    pushNameGroup('FeatUITooltipTextNameID', params.featUiTooltipTextNames)
    pushNameGroup('SampleTextNameID', params.sampleTextNames)
    for (const paramName of params.paramUiLabelNames) {
      pushNameGroup('ParamUILabelNameID', [paramName])
    }
    for (const character of params.characters) {
      groupLines.push(`    Character ${formatCharacter(character)};`)
    }
    if (groupLines.length === 0) return []
    lines.push('  cvParameters {', ...groupLines, '  };')
  }

  if (params.kind === 'size') {
    const hasRange =
      params.subfamilyIdentifier !== 0 ||
      params.rangeStart !== 0 ||
      params.rangeEnd !== 0
    lines.push(
      hasRange
        ? `  parameters ${formatDecipoints(params.designSize)} ${params.subfamilyIdentifier} ${formatDecipoints(params.rangeStart)} ${formatDecipoints(params.rangeEnd)};`
        : `  parameters ${formatDecipoints(params.designSize)} 0;`
    )
    for (const name of params.subfamilyNames) {
      lines.push(`  sizemenuname "${escapeFeaNameString(name.text)}";`)
    }
  }

  return lines.length > 0 ? [{ kind: 'Raw', value: lines.join('\n') }] : []
}

const featureStatements = (
  feature: FeatureRecord,
  lookupById: Map<string, LookupRecord>
): FeaNode[] => {
  if (feature.tag !== 'aalt') {
    return feature.entries.flatMap((entry) =>
      featureEntryStatements(entry, lookupById)
    )
  }

  const lookupIds = new Set(feature.entries.flatMap((entry) => entry.lookupIds))
  return [...lookupIds].flatMap((lookupId) => {
    const lookup = lookupById.get(lookupId)
    return lookup ? [lookupReferenceStatement(lookup)] : []
  })
}

function collectNestedLookupIds(
  lookupId: string,
  lookupById: Map<string, LookupRecord>,
  activeLookupIds: Set<string>
) {
  const lookup = lookupById.get(lookupId)
  if (!lookup) return

  for (const nestedLookupId of lookup.rules.flatMap(
    getNestedLookupReferences
  )) {
    if (activeLookupIds.has(nestedLookupId)) continue
    activeLookupIds.add(nestedLookupId)
    collectNestedLookupIds(nestedLookupId, lookupById, activeLookupIds)
  }
}

const orderLookupsForSerialization = (
  lookups: LookupRecord[],
  activeLookupIds: Set<string>
) => {
  const lookupById = new Map(lookups.map((lookup) => [lookup.id, lookup]))
  const orderedLookups: LookupRecord[] = []
  const visitedLookupIds = new Set<string>()
  const visitingLookupIds = new Set<string>()

  const visitLookup = (lookupId: string) => {
    if (visitedLookupIds.has(lookupId)) return
    const lookup = lookupById.get(lookupId)
    if (!lookup) return
    if (visitingLookupIds.has(lookupId)) {
      return
    }

    visitingLookupIds.add(lookupId)
    for (const nestedLookupId of lookup.rules.flatMap(
      getNestedLookupReferences
    )) {
      if (activeLookupIds.has(nestedLookupId)) {
        visitLookup(nestedLookupId)
      }
    }
    visitingLookupIds.delete(lookupId)
    visitedLookupIds.add(lookupId)
    orderedLookups.push(lookup)
  }

  for (const lookup of lookups) {
    if (activeLookupIds.has(lookup.id)) {
      visitLookup(lookup.id)
    }
  }

  return orderedLookups
}

const getRawFeatureTextForOutput = (state: OpenTypeFeaturesState) => {
  const rawFeatureText = getRawFeatureText(state, { includeDisabled: false })
  if (!rawFeatureText) return null

  const isClassifiedIntoModel = (state.sourceSections ?? []).some(
    (section) =>
      section.textRef === 'rawFeatureText' &&
      section.meta?.classifiedIntoModel === true &&
      section.meta?.preserveRawTextInGeneratedFea === false
  )
  return isClassifiedIntoModel ? null : rawFeatureText
}

export const buildFeaDocument = (state: OpenTypeFeaturesState) => {
  const rawFeatureTextForOutput = getRawFeatureTextForOutput(state)
  const lookupById = new Map(state.lookups.map((lookup) => [lookup.id, lookup]))
  const lookupNameById = new Map(
    state.lookups.map((lookup) => [lookup.id, lookup.name])
  )
  const gdefDerivedGlyphClasses = [
    ...(state.gdef?.markGlyphSets ?? []),
    ...(state.gdef?.markAttachClasses ?? []),
  ]
  const glyphClassNameById = new Map([
    ...state.glyphClasses.map(
      (glyphClass) => [glyphClass.id, glyphClass.name] as const
    ),
    ...gdefDerivedGlyphClasses.map(
      (glyphClass) => [glyphClass.id, glyphClass.name] as const
    ),
  ])
  const markClassNameById = new Map(
    state.markClasses.map((markClass) => [markClass.id, markClass.name])
  )
  const activeLookupIds = new Set(
    state.features
      .filter((feature) => feature.isActive)
      .flatMap((feature) => feature.entries.flatMap((entry) => entry.lookupIds))
  )
  for (const lookupId of [...activeLookupIds]) {
    collectNestedLookupIds(lookupId, lookupById, activeLookupIds)
  }
  const orderedLookups = orderLookupsForSerialization(
    state.lookups,
    activeLookupIds
  )

  const referencedGdefClassIds = new Set(
    orderedLookups.flatMap((lookup) => [
      ...(lookup.markAttachmentClassId ? [lookup.markAttachmentClassId] : []),
      ...(lookup.markFilteringSetClassId
        ? [lookup.markFilteringSetClassId]
        : []),
    ])
  )
  const stateGlyphClassIds = new Set(
    state.glyphClasses.map((glyphClass) => glyphClass.id)
  )
  const referencedGdefGlyphClasses = gdefDerivedGlyphClasses.filter(
    (glyphClass) =>
      referencedGdefClassIds.has(glyphClass.id) &&
      !stateGlyphClassIds.has(glyphClass.id)
  )

  const statements: FeaNode[] = [
    ...headerComments.map((value) => ({ kind: 'Comment' as const, value })),
    ...(rawFeatureTextForOutput
      ? [{ kind: 'Raw' as const, value: rawFeatureTextForOutput }]
      : []),
    ...state.languagesystems.map((languageSystem) => ({
      kind: 'LanguageSystem' as const,
      script: languageSystem.script,
      language: languageSystem.language,
    })),
    ...state.glyphClasses.map((glyphClass) => ({
      kind: 'GlyphClass' as const,
      name: glyphClass.name,
      glyphs: glyphClass.glyphs,
      classId: glyphClass.id,
    })),
    ...referencedGdefGlyphClasses.map((glyphClass) => ({
      kind: 'GlyphClass' as const,
      name: glyphClass.name,
      glyphs: glyphClass.glyphs,
      classId: glyphClass.id,
    })),
    ...state.markClasses.flatMap((markClass) =>
      markClass.marks.map((mark) => ({
        kind: 'MarkClass' as const,
        glyph: mark.glyph,
        anchor: mark.anchor,
        className: markClass.name,
      }))
    ),
    ...(state.gdef
      ? [
          {
            kind: 'GdefTable' as const,
            gdef: state.gdef,
          },
        ]
      : []),
    ...orderedLookups.map((lookup) =>
      lookupToBlock(
        lookup,
        markClassNameById,
        glyphClassNameById,
        lookupNameById
      )
    ),
    ...state.features
      .filter((feature) => feature.isActive)
      .map((feature) => ({
        kind: 'FeatureBlock' as const,
        tag: feature.tag,
        featureId: feature.id,
        statements: [
          ...featureParamsStatements(feature.featureParams),
          ...featureStatements(feature, lookupById),
        ],
      })),
  ]

  return {
    kind: 'Document' as const,
    statements,
  }
}
