import { describe, expect, it } from 'vitest'
import { createEmptyOpenTypeFeaturesState } from 'src/lib/openTypeFeatures/defaults'
import {
  hasActiveManagedFeatureText,
  selectUfoFeatureText,
} from 'src/lib/openTypeFeatures/legacyFeatureText'
import type { OpenTypeFeaturesState } from 'src/lib/openTypeFeatures/types'
import type { FontData } from 'src/store/types'

const makeFontData = (openTypeFeatures?: OpenTypeFeaturesState): FontData => ({
  glyphs: {},
  unitsPerEm: 1000,
  features: {
    language: 'fea',
    text: 'feature liga { sub f i by f_i; } liga;\n',
    customData: {},
  },
  openTypeFeatures,
})

const makeManagedState = (isActive: boolean): OpenTypeFeaturesState => ({
  ...createEmptyOpenTypeFeaturesState(),
  features: [
    {
      id: 'feature_liga',
      tag: 'liga',
      isActive,
      origin: 'manual',
      entries: [
        {
          id: 'feature_liga_DFLT_dflt',
          script: 'DFLT',
          language: 'dflt',
          lookupIds: ['lookup_liga_manual'],
        },
      ],
    },
  ],
  lookups: [
    {
      id: 'lookup_liga_manual',
      name: 'lookup_liga_manual',
      table: 'GSUB',
      lookupType: 'ligatureSubst',
      lookupFlag: {},
      rules: [
        {
          id: 'rule_f_i',
          kind: 'ligatureSubstitution',
          components: ['f', 'i'],
          replacement: 'f_i',
          meta: { origin: 'manual' },
        },
      ],
      editable: true,
      origin: 'manual',
    },
  ],
})

describe('UFO feature text selection', () => {
  it('preserves legacy feature text when no managed IR feature is active', () => {
    expect(selectUfoFeatureText(makeFontData())).toBe(
      'feature liga { sub f i by f_i; } liga;\n'
    )
  })

  it('uses generated FEA when managed IR has active features', () => {
    const featureText = selectUfoFeatureText(
      makeFontData(makeManagedState(true))
    )

    expect(featureText).toContain('Generated by Kumiko Font Editor.')
    expect(featureText).toContain('# kumiko-rule-id: rule_f_i')
    expect(featureText).toContain('sub f i by f_i;')
  })

  it('does not replace legacy feature text with inactive managed IR', () => {
    const state = makeManagedState(false)

    expect(hasActiveManagedFeatureText(state)).toBe(false)
    expect(selectUfoFeatureText(makeFontData(state))).not.toContain(
      'Generated by Kumiko Font Editor.'
    )
  })
})
