import { describe, expect, it } from 'vitest'
import { createEmptyOpenTypeFeaturesState } from 'src/lib/openTypeFeatures/defaults'
import {
  hasExportableFeatureText,
  selectUfoFeatureText,
} from 'src/lib/openTypeFeatures/ufoFeatureText'
import type { OpenTypeFeaturesState } from 'src/lib/openTypeFeatures/types'
import type { FontData } from 'src/store/types'

const makeFontData = (openTypeFeatures?: OpenTypeFeaturesState): FontData => ({
  glyphs: {},
  unitsPerEm: 1000,
  openTypeFeatures,
})

const makeManagedState = (isActive: boolean): OpenTypeFeaturesState => ({
  ...createEmptyOpenTypeFeaturesState(),
  features: [
    {
      id: 'feature_liga',
      tag: 'liga',
      isActive,
      origin: 'manual',
      entries: [
        {
          id: 'feature_liga_DFLT_dflt',
          script: 'DFLT',
          language: 'dflt',
          lookupIds: ['lookup_liga_manual'],
        },
      ],
    },
  ],
  lookups: [
    {
      id: 'lookup_liga_manual',
      name: 'lookup_liga_manual',
      table: 'GSUB',
      lookupType: 'ligatureSubst',
      lookupFlag: {},
      rules: [
        {
          id: 'rule_f_i',
          kind: 'ligatureSubstitution',
          components: ['f', 'i'],
          replacement: 'f_i',
          meta: { origin: 'manual' },
        },
      ],
      editable: true,
      origin: 'manual',
    },
  ],
})

describe('UFO feature text selection', () => {
  it('omits features.fea when no Kumiko feature model data exists', () => {
    expect(selectUfoFeatureText(makeFontData())).toBeNull()
  })

  it('uses generated FEA when managed IR has active features', () => {
    const featureText = selectUfoFeatureText(
      makeFontData(makeManagedState(true))
    )

    expect(featureText).toContain('Generated by Kumiko Font Editor.')
    expect(featureText).toContain('# kumiko-rule-id: rule_f_i')
    expect(featureText).toContain('sub f i by f_i;')
  })

  it('emits raw prelude even when no managed feature is active', () => {
    const state: OpenTypeFeaturesState = {
      ...createEmptyOpenTypeFeaturesState(),
      rawFeatureText: '@Code = [hyphen greater];',
    }

    expect(hasExportableFeatureText(state)).toBe(true)
    expect(selectUfoFeatureText(makeFontData(state))).toContain(
      '@Code = [hyphen greater];'
    )
  })

  it('uses generated FEA for managed IR data even when a feature is inactive', () => {
    const state = makeManagedState(false)

    expect(hasExportableFeatureText(state)).toBe(true)
    expect(selectUfoFeatureText(makeFontData(state))).toContain(
      'Generated by Kumiko Font Editor.'
    )
  })
})
